### PR TITLE
fix: isFilePath not working on windows

### LINKED ISSUE #3: Troubles with isFilePath on windows
Hi,

I'm having trouble getting isFilePath to match on windows - and therefore am not getting extensions being resolved.

If I give an absolute resolved path to alias, the regex does not pass on windows (because its `c:\a\b` not `\a\b\`

If I give a relative path, it doesn't work because I need `../` at the begining.

I'm currently solving this by passing this alias

```
'alias': './../' + path.relative(path.resolve('.'), path_i_want)
```

perhaps the isFilePath could be `/^(\.{0,2}[\/\\]|[a-z]:\/\/)/i` - what do you think?

### PR DESCRIPTION
**Pull request by papa-zakari**
Closes #3 
## 

Uses [`path.sep`](https://nodejs.org/dist/latest-v6.x/docs/api/path.html#path_path_sep) to generate a `RegExp` that works for both Windows and UNIX based systems.

**Windows:** `/^\.?\\/`
**Linux/OSX:** `/^\.?\//`

### CODE REVIEW

**Review by cdunford — APPROVED** [review]
This looks like a good change. It's not entirely clear what the expectation of isFilePath is - perhaps using path.parse and processing the output would be easier to understand.

**Comment by cdunford** [comment]
My issue seems to stem from the fact that I have absolute paths on windows. I added the following outside of if(isFilePath(updatedId)) and it resolves my issue:

```
 var match = resolve.map(function (ext) {
    return updatedId + ext;
  }).find(exists);

  if (match) {
    return match;
  }
```

**Comment by gaearon** [comment]
@Rich-Harris Could you take a look? Seems like without a fix for this (I’m not sure if it’s the right fix) we can’t build React on Windows: https://github.com/facebook/react/issues/9350#issuecomment-292470428.

**Comment by Rich-Harris** [comment]
So, I created a dummy PR (#16) to try to coax Appveyor into testing this branch, and some tests are failing — possibly unrelated to #3. I haven't yet had a chance to investigate, will try and take a look soon. [Appveyor output is here](https://ci.appveyor.com/project/Rich-Harris/rollup-plugin-alias/build/1.0.3/job/rdvlwcxgoxne5vw9) if anyone is interested.

**Comment by papa-zakari** [comment]
> So, I created a dummy PR (#16) to try to coax Appveyor into testing this branch, and some tests are failing — possibly unrelated to #3.

Nice! Is this a matter of tests needing an update or is there an issue with the implementation? 

After a quick glance at the Appveyor output, it almost seems like this plugin assumes the existence of [rollup-plugin-node-resolve](https://github.com/rollup/rollup-plugin-node-resolve).

Here is a [link](http://regexr.com/3fn34) to an example of the resulting regex on windows. I added the `g` and `m` flags for demonstration purposes.

Let me know if there is anything I can do to help.

**Comment by Rich-Harris** [comment]
> Nice! Is this a matter of tests needing an update or is there an issue with the implementation?

I assume it's an issue(s) with the implementation. Not entirely sure, though — if anyone can check out the `gh-3` branch (includes this branch, updated to latest `master`) on a Windows machine and see if they can get their head round it I'd be very grateful.

**Comment by papa-zakari** [comment]
@Rich-Harris I got this working on macOS 10.12.4 as well as Windows 10 (running in a vm).

I changed the implementation to first convert windows paths into the posix equivalent and then further parsing/updates to the ids use the [`path.posix`](https://nodejs.org/dist/latest-v7.x/docs/api/path.html#path_path_posix) module to get the posix behavior regardless of the platform. This may allow for better compatibility with other plugins down stream.

If this looks promising, I can do some cleanup on the implementation and tests.

**Comment by papa-zakari** [comment]
Here is a [diff](https://github.com/rollup/rollup-plugin-alias/compare/gh-3...zacharygolba:fix-windows-file-paths) against the `gh-3` branch for better context.

**Comment by Rich-Harris** [comment]
@zacharygolba thank you! looks like green lights all round. I'll cut a new release now so that we can finally close #3, I don't think there's any great need for further cleanup but totally up to you

🍻

**Comment by papa-zakari** [comment]
@Rich-Harris Anytime! I'm happy to help out. 😃

**Pull request merged**
