### PR TITLE
Add support for importing index.js from aliased directories path

### LINKED ISSUE #37: Unable to import module as directory
I cannot load modules as `import x from '@/directory'` (where `directory` contains `index.js`).

My config:

```
alias({
    '@': path.join(__dirname, './src')
})
```

**What doesn't work**
`import x from '@/directory'`

**What works**
`import x from './directory'`
`import x from '@/directory/index.js'`

### PR DESCRIPTION
**Pull request by soanvig**
Fix #37 

I have written new tests, and tested it in one of my local projects. Everything works I think, but one may look into tests, because I'm not expert in testing.

### CODE REVIEW

**Comment by soanvig** [comment]
Appveyor test returns false, while Travis true. Not sure if my patch destroyed something, but it shouldn't. This may be false negative check, at least for that PR.

**Comment by leesiongchan** [comment]
Why is this hasn't been merged?

**Comment by soanvig** [comment]
Repo is inactive for a long time. I could be eager to take ownership if I maintain more projects, that use Rollup. For now I have only one or two such.

**Comment by soanvig** [comment]
You may want to use directly my fork (npm supports external repositories). You may see Google, if you don't know what Im talking about.

**Review by AndrewKiri — APPROVED** [review]

**Comment by frostney** [comment]
Hi @soanvig, thank you for your pull request. I've commented on the corresponding issue (#37) as well.

The idea here is that Rollup plugins have a specific responsibility. For this plugin it's to only provide aliases, but not to enhance the resolution algorithm in any other way.

The recommended approach is to use `rollup-plugin-node-resolve` which allows to resolve `index.js` files and use it in conjuction with `rollup-plugin-alias`. Please feel free to open an issue if that doesn't work you.

If you think this is still unresolved, leave a comment and I'm happy to discuss this further.

**Pull request closed without merging**
