### PR TITLE
fix(win32): make VOLUME regex case-independent

### PR DESCRIPTION
**Pull request by MarekLacoAXA**
Because drive letters are lower case (tested on Win10), and so isFilePath(updatedId) fails with VOLUME regexp being upper case only.

Thanks for merging this soon (if all is okay)!

### CODE REVIEW

**Comment by MarekLacoAXA** [comment]
Hi @lukastaegert ! Could you please review/merge? Thx!

**Comment by lukastaegert** [comment]
Hi, sorry for letting you wait. I'm slightly busy with preparing a presentation at the moment but will give it a look soon.

**Review by lukastaegert — APPROVED** [review]
Usually I would love a test, also for documentation, but I guess this should work

**Comment by MarekLacoAXA** [comment]
Thanks!!!

**Pull request merged**
